version: '3.4'

networks:
  alembicmysql:
    external: false

services:
  db:
    image: mysql
    container_name: alembicmysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      alembicmysql:
        aliases:
          - db
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-u", $$MYSQL_USER, --password=$$MYSQL_PASSWORD]
      timeout: 10s
      retries: 5
      start_period: 10s
  migrations:
    build: ./jobs/migrations
    container_name: alembicmysql_migrations_job
    networks:
      - alembicmysql
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  etl:
    build: ./jobs/etl
    container_name: alembicmysql_etl_job
    networks:
      - alembicmysql
    env_file:
      - .env
    volumes:
      - ./jobs/etl/outputs:/etl/outputs
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_started
  jupyter:
    build: ./jupyter
    container_name: alembicmysql_jupyter
    restart: always
    networks:
      - alembicmysql
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks
    depends_on:
      - etl