version: '3.4'

networks:
  alembicmysql:
    external: false

services:
  db:
    image: mysql
    container_name: alembicmysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      alembicmysql:
        aliases:
          - db
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  migrations:
    build: ./jobs/migrations
    container_name: alembicmysql_migrations_job
    networks:
      - alembicmysql
    env_file:
      - .env
    depends_on:
      - db
  etl:
    build: ./jobs/etl
    container_name: alembicmysql_etl_job
    networks:
      - alembicmysql
    env_file:
      - .env
    volumes:
      - ./jobs/etl/outputs:/etl/outputs
    depends_on:
      - migrations
  jupyter:
    build: ./jupyter
    container_name: alembicmysql_jupyter
    restart: always
    networks:
      - alembicmysql
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks
    depends_on:
      - etl